### ISSUE TITLE
Missing Linux implementation

### ISSUE THREAD

**Issue by DavBfr** [rustui/hid#2]
The same as macOS should work.

**Comment by rustui** [comment]
You should be right, the size of wchar_t is same on Linux and macOS. But I don't have a Linux machine to test that it really works, so code contributions are welcome.

**Comment by DavBfr** [comment]
Can you provide your scripts to generate the generated_bindings.dart files?
I'll do the Linux.

**Comment by rustui** [comment]
Thanks! I forgot to add the build script to pubspec.yaml. It should be this:
```
ffigen:
  name: "Api"
  output: "lib/generated_bindings.dart"
  compiler-opts:
    - "-Wno-nullability-completeness"
  functions:
    rename:
      "hid_(.*)": "$1"
  headers:
    entry-points:
      - "hidapi.h"
    include-directives:
      - "hidapi.h"
```

[hidapi.h](https://github.com/libusb/hidapi/blob/master/hidapi/hidapi.h)
[ffigen](https://pub.dev/packages/ffigen)
